--상품 설명을 추가하기 위해
--O_PRODUCT 테이블에 PDT_DESCRIPTION 칼럼 추가 및 값 추가

ALTER TABLE O_PRODUCT
ADD ("PDT_DESCRIPTION" NVARCHAR2(200));

SELECT *
FROM O_PRODUCT;

UPDATE O_PRODUCT SET PDT_DESCRIPTION = '순하고 깔끔한 저자극 리무버'
WHERE PDT_ID = 169;

UPDATE O_PRODUCT SET PDT_DESCRIPTION = '광택과 볼륨감을 더하는 탑젤'
WHERE PDT_ID = 170;

UPDATE O_PRODUCT SET PDT_DESCRIPTION = '식물성 오일로 손발톱을 건강하게'
WHERE PDT_ID = 171;

UPDATE O_PRODUCT SET PDT_DESCRIPTION = '강력한 보호막을 형성하는 네일 강화제'
WHERE PDT_ID = 172;

UPDATE O_PRODUCT SET PDT_DESCRIPTION = '부착, 제거 팁으로 전문가처럼'
WHERE PDT_ID = 173;

UPDATE O_PRODUCT SET PDT_DESCRIPTION = '유지력을 높여주는 네일 프라이머'
WHERE PDT_ID = 174;

UPDATE O_PRODUCT SET PDT_DESCRIPTION = '안전하고 깔끔한 손·발톱 관리'
WHERE PDT_ID = 175;

UPDATE o_product
SET pdt_count = 50
WHERE pdt_id BETWEEN 1 AND 182;
--
UPDATE o_pdtoption
SET opt_count = 50
WHERE opt_id BETWEEN 1 AND 28;

COMMIT;
