-- 테이블 전부 삭제
-- ctrl + A
-- ctrl + ENTER 반복

DROP TABLE O_ADDRESS;
DROP TABLE O_ASK;
DROP TABLE O_AUTH;
DROP TABLE O_CART;
DROP TABLE O_CARTLIST;
DROP TABLE O_CATEGORY;
DROP TABLE O_COLOR;
DROP TABLE O_COMMENT;
DROP TABLE O_COUPON;
DROP TABLE O_DESIGN;
DROP TABLE O_EVENT;
DROP TABLE O_FAQ;
DROP TABLE O_FAQCATEGORY;
DROP TABLE O_ISSUEDCOUPON;
DROP TABLE O_LINEUP;
DROP TABLE O_MEMBERSHIP;
DROP TABLE O_NOTICE;
DROP TABLE O_ORDDETAIL;
DROP TABLE O_ORDER;
DROP TABLE O_PAYMENT;
DROP TABLE O_PDTCOLOR;
DROP TABLE O_PDTDESIGN;
DROP TABLE O_PDTLINEUP;
DROP TABLE O_PDTOPTION;
DROP TABLE O_PRODUCT;
DROP TABLE O_REVIEW;
DROP TABLE O_REVURL;
DROP TABLE O_SUBCATEGORY;
DROP TABLE O_USER;

-- 드래그하고 엔터키 반복해도 테이블 안지워지면 사용 (제약조건까지 제거)
--DROP TABLE O_ADDRESS CASCADE CONSTRAINTS;
--DROP TABLE O_ASK CASCADE CONSTRAINTS;
--DROP TABLE O_AUTH CASCADE CONSTRAINTS;
--DROP TABLE O_CART CASCADE CONSTRAINTS;
--DROP TABLE O_CARTLIST CASCADE CONSTRAINTS;
--DROP TABLE O_CATEGORY CASCADE CONSTRAINTS;
--DROP TABLE O_COLOR CASCADE CONSTRAINTS;
--DROP TABLE O_COMMENT CASCADE CONSTRAINTS;
--DROP TABLE O_COUPON CASCADE CONSTRAINTS;
--DROP TABLE O_DESIGN CASCADE CONSTRAINTS;
--DROP TABLE O_EVENT CASCADE CONSTRAINTS;
--DROP TABLE O_FAQ CASCADE CONSTRAINTS;
--DROP TABLE O_FAQCATEGORY CASCADE CONSTRAINTS;
--DROP TABLE O_ISSUEDCOUPON CASCADE CONSTRAINTS;
--DROP TABLE O_LINEUP CASCADE CONSTRAINTS;
--DROP TABLE O_MEMBERSHIP CASCADE CONSTRAINTS;
--DROP TABLE O_NOTICE CASCADE CONSTRAINTS;
--DROP TABLE O_ORDDETAIL CASCADE CONSTRAINTS;
--DROP TABLE O_ORDER CASCADE CONSTRAINTS;
--DROP TABLE O_PAYMENT CASCADE CONSTRAINTS;
--DROP TABLE O_PDTCOLOR CASCADE CONSTRAINTS;
--DROP TABLE O_PDTDESIGN CASCADE CONSTRAINTS;
--DROP TABLE O_PDTLINEUP CASCADE CONSTRAINTS;
--DROP TABLE O_PDTOPTION CASCADE CONSTRAINTS;
--DROP TABLE O_PRODUCT CASCADE CONSTRAINTS;
--DROP TABLE O_REVIEW CASCADE CONSTRAINTS;
--DROP TABLE O_REVURL CASCADE CONSTRAINTS;
--DROP TABLE O_SUBCATEGORY CASCADE CONSTRAINTS;
--DROP TABLE O_USER CASCADE CONSTRAINTS;
